name: CI

on:
  push:
    branches: [ main, work ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements-tradingview.txt

      # ⛔️ Removed flake8 entirely

      - name: Run tests
        run: pytest -q

      - name: Send webhook
        if: success()
        run: |
          if [ -n "$WEBHOOK_URL" ]; then
            curl -X POST -H "Content-Type: application/json" \
              -d '{"status":"success"}' "$WEBHOOK_URL"
          fi
