name: CI

on:
  push:
    branches: [main, work]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements-tradingview.txt

      - name: Lint with flake8
        run: |
          echo "Running flake8 safely on all Python files..."
          git ls-files -z '*.py' | xargs -0 flake8 \
            --exclude=node_modules,venv,__pycache__,.git \
            --ignore=E501,F401,E302 \
            --exit-zero || ec

      - name: Run tests
        run: pytest -q

      - name: Send webhook
        if: success()
        run: |
          if [[ -n "$WEBHOOK_URL" ]]; then
            curl -X POST -H "Content-Type: application/json" \
              -d '{"status":"success"}' "$WEBHOOK_URL"
          fi
